version: '3.8'

services:
  gophish:
    build: .
    ports:
      - "3333:3333"
      - "8080:8080"
      - "8443:8443"
      - "80:80"
    environment:
      - DB_NAME=mysql
      - DB_FILE_PATH=gophish:gophish@tcp(db:3306)/gophish?charset=utf8&parseTime=True&loc=Local
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=gophish
      - MYSQL_USER=gophish
      - MYSQL_PASSWORD=gophish
      - MYSQL_ROOT_PASSWORD=gophish
    volumes:
      - gophish_db_data:/var/lib/mysql
    restart: always

volumes:
  gophish_db_data:
